/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dangnhap;



import java.util.ArrayList;
import java.util.List;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;


public class MainApp extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("scene_list.fxml"));
        
        Scene scene = new Scene(root);
    
        stage.setScene(scene);
        stage.show();
        //scene.getStylesheets().add(getClass().getResource("styles.css").toExternalForm());
        
        
    }

    public static void main(String[] args) {
        launch(args);
        
        
    }

}
