/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bt15;



import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Polygon;
import javafx.stage.Stage;


public class MainApp extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        

         Pane root = new Pane();
        
        Canvas canvas = new Canvas(300, 300);
        GraphicsContext gc = canvas.getGraphicsContext2D();
        
       
        
        
        gc.setFill(Color.WHITE);
        gc.setStroke(Color.BLACK);
        gc.setLineWidth(2);
        gc.fillOval(110, 150, 80, 80);
        gc.strokeOval(110, 150, 80, 80);

        

        gc.setFill(Color.WHITE);
        gc.setStroke(Color.BLACK);
        gc.setLineWidth(2);
        gc.beginPath();
        gc.moveTo(150, 30);    
        gc.lineTo(30, 170);    
        gc.lineTo(270, 170);   
        gc.closePath();
        gc.fill();
        gc.stroke();
        

        gc.beginPath();
        gc.moveTo(125, 60);
        gc.lineTo(120, 20);
        gc.lineTo(138, 45);
        gc.closePath();
        gc.fill();
        gc.stroke();

        gc.beginPath();
        gc.moveTo(175, 60);
        gc.lineTo(175, 20);
        gc.lineTo(165, 45);
        gc.closePath();
        gc.fill();
        gc.stroke();

        gc.setFill(Color.WHITE);
        gc.setStroke(Color.RED);
        gc.beginPath();
        gc.moveTo(135, 120);
        gc.lineTo(165, 120);
        gc.lineTo(150, 140);
        gc.closePath();
        gc.fill();
        gc.stroke();

        gc.setFill(Color.WHITE);
        gc.setStroke(Color.BLACK);        
        gc.fillOval(105, 200, 40, 40);
        gc.strokeOval(105, 200, 40, 40);
        
        gc.fillOval(155, 200, 40, 40);
        gc.strokeOval(155, 200, 40, 40);
        
        gc.setFill(Color.WHITE);
        gc.setStroke(Color.RED);
        gc.fillOval(120, 210, 10, 10);
        gc.strokeOval(120, 210, 10, 10);
        
        gc.fillOval(170, 210, 10, 10);
        gc.strokeOval(170, 210, 10, 10);
        
        root.getChildren().add(canvas);
        
        Scene scene = new Scene(root, 300, 300);
        stage.setTitle("Triangle Cat");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
        
    }

}