/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bt15;



import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.ArcType;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Polygon;
import javafx.stage.Stage;


public class MainApp extends Application {

    double mx, my;
    boolean isDrawing = false; 

    @Override
    public void start(Stage stage) throws Exception {
        

        Pane root = new Pane();
        
        Button drawButton = new Button("Vẽ");
        drawButton.setOnAction(event -> {
            isDrawing = !isDrawing;
            if (isDrawing) {
                drawButton.setText("Ngừng vẽ");
            } else {
                drawButton.setText("Vẽ");
            }
        });
        Canvas canvas = new Canvas(300, 300);
        GraphicsContext gc = canvas.getGraphicsContext2D();
        

        
        gc.setFill(Color.WHITE);
        gc.setStroke(Color.BLACK);
        gc.setLineWidth(2);
        gc.fillOval(110, 150, 80, 80);
        gc.strokeOval(110, 150, 80, 80);

        

        gc.setFill(Color.WHITE);
        gc.setStroke(Color.BLACK);
        gc.setLineWidth(2);
        gc.beginPath();
        gc.moveTo(150, 30);    
        gc.lineTo(30, 170);    
        gc.lineTo(270, 170);   
        gc.closePath();
        gc.fill();
        gc.stroke();
        

        gc.beginPath();
        gc.moveTo(125, 60);
        gc.lineTo(120, 20);
        gc.lineTo(138, 45);
        gc.closePath();
        gc.fill();
        gc.stroke();

        gc.beginPath();
        gc.moveTo(175, 60);
        gc.lineTo(175, 20);
        gc.lineTo(165, 45);
        gc.closePath();
        gc.fill();
        gc.stroke();

        gc.setFill(Color.WHITE);
        gc.setStroke(Color.RED);
        gc.beginPath();
        gc.moveTo(135, 120);
        gc.lineTo(165, 120);
        gc.lineTo(150, 140);
        gc.closePath();
        gc.fill();
        gc.stroke();

        gc.setFill(Color.WHITE);
        gc.setStroke(Color.BLACK);        
        gc.fillOval(105, 200, 40, 40);
        gc.strokeOval(105, 200, 40, 40);
        
        gc.fillOval(155, 200, 40, 40);
        gc.strokeOval(155, 200, 40, 40);
        
        gc.setFill(Color.WHITE);
        gc.setStroke(Color.RED);
        gc.strokeArc(110, 220, 5, 10, 90, 160,ArcType.OPEN);
        gc.strokeArc(120, 220, 5, 10, 90, -160, ArcType.OPEN);

        gc.strokeArc(165, 220, 5, 10, 90, 160, ArcType.OPEN);
        gc.strokeArc(175, 220, 5, 10, 90, -160, ArcType.OPEN);
        
        DrawWithMouse(canvas);
        root.getChildren().add(canvas);
        root.getChildren().add(drawButton);

        
        Scene scene = new Scene(root, 300, 300);
        stage.setTitle("Triangle Cat");
        stage.setScene(scene);
        stage.show();
    }
    public void DrawWithMouse(Canvas cv){
        GraphicsContext gc = cv.getGraphicsContext2D();
        gc.setLineWidth(2);
        gc.setStroke(Color.BLACK);
        cv.addEventHandler(MouseEvent.MOUSE_PRESSED, event -> {
            if(isDrawing){
                
                mx = event.getX();
                my = event.getY();
            }
        });

        cv.addEventHandler(MouseEvent.MOUSE_DRAGGED, event -> {
           if(isDrawing){

               gc.strokeLine(mx, my, event.getX(), event.getY());
               
               mx = event.getX();
               my = event.getY();
            }
        });

      
    }
    public static void main(String[] args) {
        launch(args);
        
    }

}
